import { useCallback, useEffect, useState } from 'react';
import { Boxes, CalendarClock, Wrench, ClipboardCheck, Check, X, Undo2, Plus } from 'lucide-react';
import { get, post, put, toApiError } from '@/lib/api';
import { useAuth } from '@/store/auth';
import { toast } from '@/store/ui';
import { CrudPage, FormField } from '@/features/crud/CrudPage';
import { Badge, Button, Card, Field, Input, Loading, Modal, PageHeader, Select, StatCard, Table, Tabs, cx } from '@/components/ui';
import { fmtDate, fmtDateTime, fmtMoney, label, tone } from '@/lib/format';
import { Dict } from '@/lib/types';

const CATS = ['ELEKTRONIK', 'MEBEL', 'KENDARAAN', 'BANGUNAN', 'ALAT_PRAKTIK', 'BUKU', 'LAINNYA'];
const COND = [['BAIK', 'Baik'], ['RUSAK_RINGAN', 'Rusak ringan'], ['RUSAK_BERAT', 'Rusak berat'], ['HILANG', 'Hilang']];
export default function Assets() {
  const { has } = useAuth();
  const canWrite = has('asset:write');
  const [tab, setTab] = useState<'inventaris' | 'pinjam' | 'pemeliharaan' | 'opname'>(canWrite ? 'inventaris' : 'pinjam');
  const [summary, setSummary] = useState<Dict | null>(null);
  useEffect(() => { if (canWrite) get<Dict>('/sarana/assets-summary').then(setSummary); }, [canWrite]);
  const assetFields: FormField[] = [{ name: 'code', label: 'Kode', required: true }, { name: 'name', label: 'Nama', required: true }, { name: 'category', label: 'Kategori', type: 'select', defaultValue: 'ELEKTRONIK', options: CATS.map((x) => ({ value: x, label: x })) }, { name: 'room_id', label: 'Ruang', type: 'async-select', source: { url: '/academic/rooms', label: 'name' } }, { name: 'location', label: 'Lokasi (teks)' }, { name: 'custodian_id', label: 'Penanggung jawab', type: 'async-select', source: { url: '/users', params: { limit: 300 }, label: 'full_name' } }, { name: 'purchase_date', label: 'Tanggal beli', type: 'date' }, { name: 'purchase_price', label: 'Harga beli', type: 'number', defaultValue: 0 }, { name: 'useful_life_years', label: 'Umur ekonomis (th)', type: 'number', defaultValue: 5 }, { name: 'salvage_value', label: 'Nilai residu', type: 'number', defaultValue: 0 }, { name: 'quantity', label: 'Jumlah unit', type: 'number', defaultValue: 1 }, { name: 'condition_status', label: 'Kondisi', type: 'select', defaultValue: 'BAIK', options: COND.map(([v, l]) => ({ value: v, label: l })) }, { name: 'status', label: 'Status', type: 'select', defaultValue: 'AKTIF', options: ['AKTIF', 'DIPINJAM', 'PERBAIKAN', 'DIHAPUSKAN'].map((x) => ({ value: x, label: x })) }, { name: 'notes', label: 'Catatan', type: 'textarea', span: 2 }];
  return (
    <div>
      <PageHeader title="Aset & Inventaris" subtitle="Inventaris, peminjaman (deteksi bentrok), pemeliharaan, penyusutan garis lurus, dan opname." />
      {summary && <div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Aset terdaftar" value={String(summary.total)} icon={<Boxes className="h-5 w-5" />} /><StatCard label="Nilai perolehan" value={fmtMoney(summary.purchase_value as number)} tone="blue" /><StatCard label="Nilai buku" value={fmtMoney(summary.book_value as number)} tone="green" /><StatCard label="Permintaan pinjam" value={String(summary.pending_bookings)} tone="accent" icon={<CalendarClock className="h-5 w-5" />} /></div>}
      <Tabs className="mb-4 w-fit" value={tab} onChange={setTab} tabs={[{ value: 'inventaris', label: 'Inventaris' }, { value: 'pinjam', label: 'Peminjaman' }, ...(canWrite ? [{ value: 'pemeliharaan' as const, label: 'Pemeliharaan' }, { value: 'opname' as const, label: 'Opname' }] : [])]} />
      {tab === 'inventaris' && <CrudPage<Dict> noHeader title="Inventaris" endpoint="/sarana/assets" entityLabel="aset" modalSize="lg" perm={{ write: 'asset:write' }} columns={[{ key: 'code', header: 'Kode', render: (r) => <code className="text-xs">{r.code as string}</code> }, { key: 'name', header: 'Nama', render: (r) => <div><div className="font-medium">{r.name as string}</div><div className="text-xs text-ink-3">{r.category as string} · {(r.room_name as string) ?? (r.location as string) ?? '-'}{Number(r.quantity) > 1 ? ` · ${r.quantity} unit` : ''}</div></div> }, { key: 'purchase_price', header: 'Perolehan', render: (r) => fmtMoney(r.purchase_price as number) }, { key: 'book_value', header: 'Nilai buku', render: (r) => <span className="text-xs">{fmtMoney(r.book_value as number)}<br /><span className="text-ink-3">susut {fmtMoney(r.depreciation_annual as number)}/th</span></span> }, { key: 'condition_status', header: 'Kondisi', render: (r) => <Badge tone={r.condition_status === 'BAIK' ? 'green' : r.condition_status === 'HILANG' ? 'red' : 'amber'}>{r.condition_status as string}</Badge> }, { key: 'status', header: 'Status', render: (r) => <Badge tone={r.status === 'AKTIF' ? 'brand' : 'gray'}>{r.status as string}</Badge> }]} filters={[{ name: 'category', label: 'Kategori', options: CATS.map((x) => ({ value: x, label: x })) }, { name: 'condition_status', label: 'Kondisi', options: COND.map(([v, l]) => ({ value: v, label: l })) }]} fields={assetFields} />}
      {tab === 'pinjam' && <Bookings />}
      {tab === 'pemeliharaan' && <CrudPage<Dict> noHeader title="Pemeliharaan" endpoint="/sarana/maintenance" entityLabel="pemeliharaan" perm={{ write: 'asset:write' }} columns={[{ key: 'scheduled_date', header: 'Jadwal', render: (r) => fmtDate(r.scheduled_date as string) }, { key: 'asset_name', header: 'Aset', render: (r) => <span>{r.asset_name as string} <span className="text-xs text-ink-3">{r.asset_code as string}</span></span> }, { key: 'type', header: 'Jenis' }, { key: 'description', header: 'Keterangan' }, { key: 'cost', header: 'Biaya', render: (r) => fmtMoney(r.cost as number) }, { key: 'status', header: 'Status', render: (r) => <Badge tone={tone(r.status as string)}>{label(r.status as string)}</Badge> }]} filters={[{ name: 'status', label: 'Status', options: ['SCHEDULED', 'IN_PROGRESS', 'DONE', 'CANCELLED'].map((x) => ({ value: x, label: label(x) })) }]} fields={[{ name: 'asset_id', label: 'Aset', type: 'async-select', required: true, source: { url: '/sarana/assets', params: { limit: 500 }, label: (r) => `${r.code} — ${r.name}` }, span: 2 }, { name: 'type', label: 'Jenis', type: 'select', defaultValue: 'RUTIN', options: ['RUTIN', 'PERBAIKAN', 'KALIBRASI'].map((x) => ({ value: x, label: x })) }, { name: 'scheduled_date', label: 'Tanggal jadwal', type: 'date', required: true }, { name: 'done_date', label: 'Tanggal selesai', type: 'date' }, { name: 'status', label: 'Status', type: 'select', defaultValue: 'SCHEDULED', options: ['SCHEDULED', 'IN_PROGRESS', 'DONE', 'CANCELLED'].map((x) => ({ value: x, label: label(x) })) }, { name: 'cost', label: 'Biaya (masuk arus kas saat DONE)', type: 'number', defaultValue: 0 }, { name: 'vendor', label: 'Vendor' }, { name: 'description', label: 'Keterangan', type: 'textarea', span: 2 }]} />}
      {tab === 'opname' && <Audits />}
    </div>
  );
}
function Bookings() {
  const { has } = useAuth();
  return <CrudPage<Dict> noHeader title="Peminjaman" endpoint="/sarana/bookings" entityLabel="peminjaman" perm={{ write: 'asset:book' }} canEdit={false}
    columns={[{ key: 'asset_name', header: 'Aset', render: (r) => <span>{r.asset_name as string} <span className="text-xs text-ink-3">{r.asset_code as string}</span></span> }, { key: 'booked_by_name', header: 'Peminjam' }, { key: 'start_at', header: 'Waktu', render: (r) => <span className="text-xs">{fmtDateTime(r.start_at as string)}<br />s.d. {fmtDateTime(r.end_at as string)}</span> }, { key: 'purpose', header: 'Keperluan' }, { key: 'status', header: 'Status', render: (r) => <Badge tone={tone(r.status as string)}>{label(r.status as string)}{r.return_condition ? ` · ${r.return_condition}` : ''}</Badge> }]}
    filters={[{ name: 'status', label: 'Status', options: ['PENDING', 'APPROVED', 'REJECTED', 'RETURNED'].map((x) => ({ value: x, label: label(x) })) }]}
    rowActions={(r, reload) => (has('asset:approve') || has('asset:write')) ? <div className="flex gap-1">{r.status === 'PENDING' && <><Button size="sm" variant="outline" icon={<X className="h-4 w-4" />} onClick={async () => { await post(`/sarana/bookings/${r.id}/reject`); reload(); }} /><Button size="sm" icon={<Check className="h-4 w-4" />} onClick={async () => { await post(`/sarana/bookings/${r.id}/approve`); reload(); }}>Setujui</Button></>}{r.status === 'APPROVED' && <Button size="sm" variant="outline" icon={<Undo2 className="h-4 w-4" />} onClick={async () => { const c = prompt('Kondisi saat kembali (BAIK/RUSAK_RINGAN/RUSAK_BERAT/HILANG):', 'BAIK'); if (!c) return; await post(`/sarana/bookings/${r.id}/return`, { condition: c }); reload(); }}>Kembali</Button>}</div> : null}
    fields={[{ name: 'asset_id', label: 'Aset', type: 'async-select', required: true, source: { url: '/sarana/assets', params: { limit: 500, status: 'AKTIF' }, label: (r) => `${r.code} — ${r.name}` }, span: 2 }, { name: 'start_at', label: 'Mulai', type: 'datetime', required: true }, { name: 'end_at', label: 'Selesai', type: 'datetime', required: true }, { name: 'purpose', label: 'Keperluan', span: 2 }]} />;
}
function Audits() {
  const [rows, setRows] = useState<Dict[] | null>(null);
  const [sel, setSel] = useState<Dict | null>(null);
  const load = useCallback(() => get<Dict[]>('/sarana/audits').then(setRows), []);
  useEffect(() => { load(); }, [load]);
  if (!rows) return <Loading />;
  return <><div className="mb-3 flex justify-end"><Button icon={<Plus className="h-4 w-4" />} onClick={async () => { const t = prompt('Judul opname:', `Opname ${new Date().getFullYear()}`); if (!t) return; await post('/sarana/audits', { title: t, audit_date: new Date().toISOString().slice(0, 10) }); load(); }}>Opname baru</Button></div>
    <Card padded={false}><Table<Dict> rows={rows} onRowClick={(r) => setSel(r)} columns={[{ key: 'audit_date', header: 'Tanggal', render: (r) => fmtDate(r.audit_date as string) }, { key: 'title', header: 'Judul' }, { key: 'status', header: 'Status', render: (r) => <Badge tone={r.status === 'CLOSED' ? 'gray' : 'blue'}>{r.status === 'CLOSED' ? 'Ditutup' : 'Berjalan'}</Badge> }, { key: 'summary', header: 'Ringkasan', render: (r) => { const s = (typeof r.summary === 'string' ? JSON.parse(r.summary) : r.summary) as Dict | null; return s ? `${s.checked}/${s.total} dicek · ${s.missing} kurang` : '-'; } }]} empty="Belum ada opname" /></Card>
    <AuditModal audit={sel} onClose={() => setSel(null)} onDone={() => { setSel(null); load(); }} /></>;
}
function AuditModal({ audit, onClose, onDone }: { audit: Dict | null; onClose: () => void; onDone: () => void }) {
  const [d, setD] = useState<Dict | null>(null);
  const [items, setItems] = useState<Dict[]>([]);
  useEffect(() => { if (audit) get<Dict>(`/sarana/audits/${audit.id}`).then((x) => { setD(x); setItems(x.items as Dict[]); }); else setD(null); }, [audit]);
  const save = async (close: boolean) => { try { await put(`/sarana/audits/${audit!.id}`, { items: items.map((i) => ({ asset_id: i.asset_id, found: i.found === '' || i.found === null || i.found === undefined ? null : Number(i.found), condition: i.condition, note: i.note })), close }); toast.success(close ? 'Opname ditutup; kondisi aset diperbarui' : 'Tersimpan'); onDone(); } catch (e) { toast.error(toApiError(e).message); } };
  const closed = d?.status === 'CLOSED';
  return <Modal open={!!audit} onClose={onClose} size="xl" title={audit?.title as string} footer={!closed && d ? <><Button variant="outline" onClick={() => save(false)}>Simpan</Button><Button icon={<ClipboardCheck className="h-4 w-4" />} onClick={() => { if (confirm('Tutup opname? Kondisi aset akan diperbarui sesuai hasil.')) save(true); }}>Simpan & tutup</Button></> : undefined}>
    {!d ? <Loading /> : <div className="max-h-[60vh] overflow-y-auto rounded-xl border border-line"><table className="w-full text-sm"><thead><tr className="bg-surface-2 text-left text-xs uppercase text-ink-3"><th className="px-3 py-2">Aset</th><th className="px-3 py-2 text-center">Tercatat</th><th className="px-3 py-2 text-center">Ditemukan</th><th className="px-3 py-2">Kondisi</th><th className="px-3 py-2">Catatan</th></tr></thead><tbody>{items.map((it, i) => <tr key={it.asset_id as string} className={cx('border-t border-line', it.found !== null && it.found !== undefined && it.found !== '' && Number(it.found) < Number(it.expected) && 'bg-red-50 dark:bg-red-900/10')}><td className="px-3 py-1.5"><div className="font-medium">{it.name as string}</div><div className="text-xs text-ink-3">{it.code as string}</div></td><td className="px-3 py-1.5 text-center">{it.expected as number}</td><td className="px-3 py-1.5 text-center"><Input type="number" disabled={closed} className="h-8 w-20 text-center" value={it.found === null || it.found === undefined ? '' : String(it.found)} onChange={(e) => setItems((a) => a.map((x, j) => (j === i ? { ...x, found: e.target.value } : x)))} /></td><td className="px-3 py-1.5"><Select disabled={closed} className="w-36" value={String(it.condition ?? 'BAIK')} onChange={(e) => setItems((a) => a.map((x, j) => (j === i ? { ...x, condition: e.target.value } : x)))} options={COND.map(([v, l]) => ({ value: v, label: l }))} /></td><td className="px-3 py-1.5"><Input disabled={closed} className="h-8" value={String(it.note ?? '')} onChange={(e) => setItems((a) => a.map((x, j) => (j === i ? { ...x, note: e.target.value } : x)))} /></td></tr>)}</tbody></table></div>}
  </Modal>;
}
export const _icons = [Wrench, Field];
