import { useCallback, useEffect, useState } from 'react';
import { Check, X, Plus, BookOpen, Briefcase } from 'lucide-react';
import { get, post, toApiError, uploadFile, fileSrc } from '@/lib/api';
import { useAuth } from '@/store/auth';
import { toast } from '@/store/ui';
import { CrudPage } from '@/features/crud/CrudPage';
import { Badge, Button, Card, EmptyState, Field, Input, Loading, Modal, PageHeader, Table, Tabs, Textarea, Progress } from '@/components/ui';
import { fmtDate, fmtDateTime, label, tone } from '@/lib/format';
import { Dict } from '@/lib/types';

export default function Internships() {
  const { has, hasRole } = useAuth();
  const canWrite = has('internship:write');
  const [tab, setTab] = useState<'penempatan' | 'mitra' | 'pembimbing'>('penempatan');
  const [journalOf, setJournalOf] = useState<Dict | null>(null);
  if (hasRole('SISWA') && !canWrite) return <StudentInternship />;
  return (
    <div>
      <PageHeader title="Prakerin / PKL" subtitle="Mitra industri, penempatan siswa, jurnal harian, dan verifikasi pembimbing." />
      {canWrite && <Tabs className="mb-4 w-fit" value={tab} onChange={setTab} tabs={[{ value: 'penempatan', label: 'Penempatan' }, { value: 'mitra', label: 'Mitra industri' }, { value: 'pembimbing', label: 'Pembimbing industri' }]} />}
      {tab === 'penempatan' && <CrudPage<Dict> noHeader title="Penempatan" endpoint="/smk/internships" entityLabel="penempatan" modalSize="lg" perm={{ write: 'internship:write' }}
        columns={[{ key: 'student_name', header: 'Siswa', render: (r) => <div><div className="font-medium">{r.student_name as string}</div><div className="text-xs text-ink-3">{r.class_name as string}</div></div> }, { key: 'partner_name', header: 'Mitra', render: (r) => <div>{r.partner_name as string}<div className="text-xs text-ink-3">{r.city as string} · {(r.mentor_name as string) ?? '-'}</div></div> }, { key: 'start_date', header: 'Periode', render: (r) => <span className="text-xs">{fmtDate(r.start_date as string)} – {fmtDate(r.end_date as string)}</span> }, { key: 'supervisor_name', header: 'Pembimbing sekolah' }, { key: 'journal_count', header: 'Jurnal', render: (r) => <span>{r.journal_count as number}{Number(r.pending_journals) > 0 && <Badge tone="amber" className="ml-1">{r.pending_journals as number} baru</Badge>}</span> }, { key: 'status', header: 'Status', render: (r) => <Badge tone={tone(r.status as string)}>{label(r.status as string)}</Badge> }, { key: 'final_score', header: 'Nilai', className: 'text-center', render: (r) => String(r.final_score ?? '-') }]}
        filters={[{ name: 'status', label: 'Status', options: ['PLANNED', 'ONGOING', 'DONE', 'CANCELLED'].map((x) => ({ value: x, label: label(x) })) }, { name: 'partner_id', label: 'Mitra', type: 'async-select', source: { url: '/smk/partners', label: 'name' } }]}
        rowActions={(r) => <Button size="sm" variant="outline" icon={<BookOpen className="h-4 w-4" />} onClick={() => setJournalOf(r)}>Jurnal</Button>}
        fields={[{ name: 'student_id', label: 'Siswa', type: 'async-select', required: true, source: { url: '/users', params: { role: 'SISWA', limit: 500 }, label: (r) => `${r.full_name}${r.class_name ? ` — ${r.class_name}` : ''}` }, span: 2 }, { name: 'partner_id', label: 'Mitra industri', type: 'async-select', required: true, source: { url: '/smk/partners', label: 'name' } }, { name: 'mentor_id', label: 'Pembimbing industri', type: 'async-select', source: { url: '/smk/mentors', label: (r) => `${r.name} (${r.partner_name})` } }, { name: 'school_supervisor_id', label: 'Pembimbing sekolah', type: 'async-select', source: { url: '/users', params: { role: 'GURU', limit: 300 }, label: 'full_name' } }, { name: 'status', label: 'Status', type: 'select', defaultValue: 'PLANNED', options: ['PLANNED', 'ONGOING', 'DONE', 'CANCELLED'].map((x) => ({ value: x, label: label(x) })) }, { name: 'start_date', label: 'Mulai', type: 'date', required: true }, { name: 'end_date', label: 'Selesai', type: 'date', required: true }, { name: 'final_score', label: 'Nilai akhir (0-100, masuk komponen PRAKTIK)', type: 'number' }, { name: 'mentor_feedback', label: 'Umpan balik industri', type: 'textarea', span: 2 }]} />}
      {tab === 'mitra' && <CrudPage<Dict> noHeader title="Mitra" endpoint="/smk/partners" entityLabel="mitra" modalSize="lg" perm={{ write: 'internship:write' }} columns={[{ key: 'name', header: 'Perusahaan', render: (r) => <div><div className="font-medium">{r.name as string}</div><div className="text-xs text-ink-3">{r.sector as string} · {r.city as string}</div></div> }, { key: 'contact_name', header: 'Kontak', render: (r) => <span className="text-xs">{r.contact_name as string}<br />{r.contact_phone as string}</span> }, { key: 'mou_number', header: 'MoU', render: (r) => r.mou_number ? <span className="text-xs">{r.mou_number as string}<br />s.d. {fmtDate(r.mou_until as string)}</span> : '-' }, { key: 'active_interns', header: 'Siswa aktif', render: (r) => `${r.active_interns}/${r.quota}` }, { key: 'mentor_count', header: 'Pembimbing', className: 'text-center' }]} fields={[{ name: 'name', label: 'Nama perusahaan', required: true, span: 2 }, { name: 'sector', label: 'Sektor' }, { name: 'city', label: 'Kota' }, { name: 'contact_name', label: 'Nama kontak' }, { name: 'contact_phone', label: 'Telepon' }, { name: 'contact_email', label: 'E-mail' }, { name: 'quota', label: 'Kuota siswa', type: 'number', defaultValue: 2 }, { name: 'mou_number', label: 'Nomor MoU' }, { name: 'mou_until', label: 'MoU berlaku s.d.', type: 'date' }, { name: 'address', label: 'Alamat', type: 'textarea', span: 2 }, { name: 'is_active', label: 'Aktif', type: 'switch', defaultValue: true }]} />}
      {tab === 'pembimbing' && <CrudPage<Dict> noHeader title="Pembimbing industri" endpoint="/smk/mentors" entityLabel="pembimbing" perm={{ write: 'internship:write' }} columns={[{ key: 'name', header: 'Nama', render: (r) => <div><div className="font-medium">{r.name as string}</div><div className="text-xs text-ink-3">{r.position as string}</div></div> }, { key: 'partner_name', header: 'Perusahaan' }, { key: 'phone', header: 'Kontak', render: (r) => <span className="text-xs">{r.phone as string}<br />{r.email as string}</span> }, { key: 'username', header: 'Akun', render: (r) => r.username ? <Badge tone="green">@{r.username as string}</Badge> : <Badge tone="gray">tanpa akun</Badge> }]} fields={[{ name: 'partner_id', label: 'Perusahaan', type: 'async-select', required: true, source: { url: '/smk/partners', label: 'name' }, span: 2 }, { name: 'name', label: 'Nama', required: true }, { name: 'position', label: 'Jabatan' }, { name: 'phone', label: 'Telepon' }, { name: 'email', label: 'E-mail', type: 'email' }, { name: 'create_account', label: 'Buatkan akun login (peran Pembimbing Industri)', type: 'switch', createOnly: true, span: 2 }]} afterSave={(row) => { const acc = row.account as Dict | undefined; if (acc) window.alert(`Akun pembimbing dibuat.\nUsername: ${acc.username}\nKata sandi sementara: ${acc.temporary_password}`); }} />}
      <JournalModal internship={journalOf} onClose={() => setJournalOf(null)} />
    </div>
  );
}
function JournalModal({ internship, onClose }: { internship: Dict | null; onClose: () => void }) {
  const { has } = useAuth();
  const [d, setD] = useState<Dict | null>(null);
  const load = useCallback(() => { if (internship) get<Dict>(`/smk/internships/${internship.id}/journals`).then(setD); else setD(null); }, [internship]);
  useEffect(() => { load(); }, [load]);
  const verify = async (id: string, status: string) => { const note = status === 'REJECTED' ? prompt('Catatan:') : null; try { await post(`/smk/journals/${id}/verify`, { status, note }); load(); } catch (e) { toast.error(toApiError(e).message); } };
  return <Modal open={!!internship} onClose={onClose} size="lg" title={`Jurnal — ${internship?.student_name ?? ''} @ ${internship?.partner_name ?? ''}`}>{!d ? <Loading /> : (d.journals as Dict[]).length === 0 ? <EmptyState title="Belum ada jurnal" /> : <ul className="divide-y divide-line">{(d.journals as Dict[]).map((j) => <li key={j.id as string} className="flex gap-3 py-3"><div className="w-24 shrink-0 text-xs font-semibold">{fmtDate(j.journal_date as string)}<div className="font-normal text-ink-3">{j.hours as number} jam</div></div><div className="min-w-0 flex-1"><p className="text-sm">{j.activity as string}</p>{j.photo_url ? <a href={fileSrc(j.photo_url as string)} target="_blank" rel="noreferrer" className="link text-xs">Lihat foto</a> : null}{j.mentor_note ? <div className="mt-1 text-xs text-ink-2">Catatan: {j.mentor_note as string}</div> : null}</div><div className="flex flex-col items-end gap-1"><Badge tone={j.status === 'VERIFIED' ? 'green' : j.status === 'REJECTED' ? 'red' : 'amber'}>{j.status === 'VERIFIED' ? 'Terverifikasi' : j.status === 'REJECTED' ? 'Ditolak' : 'Menunggu'}</Badge>{has('internship:journal_verify') && j.status === 'SUBMITTED' && <div className="flex gap-1"><Button size="icon" variant="ghost" icon={<X className="h-4 w-4 text-red-600" />} onClick={() => verify(j.id as string, 'REJECTED')} /><Button size="icon" variant="ghost" icon={<Check className="h-4 w-4 text-emerald-600" />} onClick={() => verify(j.id as string, 'VERIFIED')} /></div>}</div></li>)}</ul>}</Modal>;
}
function StudentInternship() {
  const [rows, setRows] = useState<Dict[] | null>(null);
  const [d, setD] = useState<Dict | null>(null);
  const [f, setF] = useState({ journal_date: new Date().toISOString().slice(0, 10), activity: '', hours: '8' });
  const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const l = await get<unknown>('/smk/internships'); const arr = (l as { data?: Dict[] }).data ?? []; setRows(arr); const cur = arr.find((x) => ['ONGOING', 'PLANNED'].includes(x.status as string)) ?? arr[0]; if (cur) setD(await get<Dict>(`/smk/internships/${cur.id}/journals`)); }, []);
  useEffect(() => { load(); }, [load]);
  if (!rows) return <Loading />;
  if (!d) return <div><PageHeader title="Prakerin" /><EmptyState title="Belum ada penempatan prakerin" icon={<Briefcase className="h-6 w-6" />} /></div>;
  const it = d.internship as Dict;
  const days = Math.max(1, (new Date(it.end_date as string).getTime() - new Date(it.start_date as string).getTime()) / 86400000);
  const elapsed = Math.min(days, Math.max(0, (Date.now() - new Date(it.start_date as string).getTime()) / 86400000));
  const submit = async () => { setBusy(true); try { let photo_file_id: string | null = null; if (file) photo_file_id = (await uploadFile('internship', file)).id; await post(`/smk/internships/${it.id}/journals`, { ...f, hours: Number(f.hours), photo_file_id }); toast.success('Jurnal dikirim'); setF({ ...f, activity: '' }); setFile(null); load(); } catch (e) { toast.error(toApiError(e).message); } finally { setBusy(false); } };
  return (
    <div>
      <PageHeader title="Prakerin Saya" subtitle={`${it.partner_name} · ${it.city ?? ''} · pembimbing ${it.mentor_name ?? '-'}`} />
      <Card className="mb-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><Badge tone={tone(it.status as string)}>{label(it.status as string)}</Badge><div className="mt-1 text-sm">{fmtDate(it.start_date as string)} – {fmtDate(it.end_date as string)}</div></div><div className="w-full sm:w-64"><div className="mb-1 flex justify-between text-xs text-ink-3"><span>Progres</span><span>{Math.round((elapsed / days) * 100)}%</span></div><Progress value={(elapsed / days) * 100} /></div>{it.final_score !== null && it.final_score !== undefined ? <div className="text-right"><div className="text-xs text-ink-3">Nilai akhir</div><div className="text-2xl font-bold text-brand-700">{String(it.final_score)}</div></div> : null}</div></Card>
      <div className="grid gap-4 lg:grid-cols-[1fr_360px]">
        <Card padded={false} title={`Jurnal harian (${(d.journals as Dict[]).length})`}>{(d.journals as Dict[]).length === 0 ? <div className="p-6"><EmptyState title="Belum ada jurnal" /></div> : <Table<Dict> dense rows={d.journals as Dict[]} columns={[{ key: 'journal_date', header: 'Tanggal', render: (r) => fmtDate(r.journal_date as string) }, { key: 'activity', header: 'Kegiatan', render: (r) => <span className="line-clamp-2 text-sm">{r.activity as string}</span> }, { key: 'hours', header: 'Jam', className: 'text-center' }, { key: 'status', header: 'Status', render: (r) => <Badge tone={r.status === 'VERIFIED' ? 'green' : r.status === 'REJECTED' ? 'red' : 'amber'}>{r.status === 'VERIFIED' ? 'OK' : r.status === 'REJECTED' ? 'Ditolak' : 'Menunggu'}</Badge> }]} />}</Card>
        <Card title="Isi jurnal hari ini"><div className="space-y-3"><Field label="Tanggal"><Input type="date" value={f.journal_date} onChange={(e) => setF({ ...f, journal_date: e.target.value })} /></Field><Field label="Kegiatan" required><Textarea rows={4} value={f.activity} onChange={(e) => setF({ ...f, activity: e.target.value })} placeholder="Apa yang dikerjakan hari ini?" /></Field><Field label="Jam kerja"><Input type="number" step="0.5" value={f.hours} onChange={(e) => setF({ ...f, hours: e.target.value })} /></Field><Field label="Foto (opsional)"><input type="file" accept="image/*" className="text-sm" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></Field><Button className="w-full" loading={busy} disabled={f.activity.length < 5} icon={<Plus className="h-4 w-4" />} onClick={submit}>Kirim jurnal</Button></div></Card>
      </div>
      <span className="hidden">{fmtDateTime('')}</span>
    </div>
  );
}
