import { Migration, table, tenantTable, fk, ID, vs, money } from './ddl';

export const m0006: Migration = {
  name: '0006_kesiswaan_finance',
  statements: [
    // ---- BK & kedisiplinan ----
    tenantTable('counseling_notes', ['student_id char(36) NOT NULL', 'counselor_id char(36) NOT NULL', 'session_date date NOT NULL', vs('category', 30, 'PRIBADI'), 'summary text NOT NULL', 'follow_up text', 'is_confidential tinyint(1) NOT NULL DEFAULT 1'], ['KEY idx_cn_student (student_id, session_date)']),
    tenantTable('discipline_rules', ['code varchar(20) NOT NULL', 'name varchar(150) NOT NULL', vs('kind', 12, 'PELANGGARAN'), 'points smallint NOT NULL DEFAULT 0', 'description text', 'is_active tinyint(1) NOT NULL DEFAULT 1'], ['UNIQUE KEY uq_dr (tenant_id, code)']),
    tenantTable('discipline_records', ['student_id char(36) NOT NULL', 'rule_id char(36) DEFAULT NULL', 'incident_date date NOT NULL', 'points smallint NOT NULL DEFAULT 0', 'description text', 'action_taken text', 'recorded_by char(36) NOT NULL', 'parent_notified tinyint(1) NOT NULL DEFAULT 0'], ['KEY idx_drec_student (student_id, incident_date)']),
    tenantTable('extracurriculars', ['code varchar(20) NOT NULL', 'name varchar(120) NOT NULL', 'description text', 'coach_id char(36) DEFAULT NULL', 'schedule_text varchar(200) DEFAULT NULL', 'quota smallint DEFAULT NULL', 'is_active tinyint(1) NOT NULL DEFAULT 1'], ['UNIQUE KEY uq_ekskul (tenant_id, code)']),
    tenantTable('extracurricular_members', ['extracurricular_id char(36) NOT NULL', 'student_id char(36) NOT NULL', 'academic_year_id char(36) DEFAULT NULL', vs('status', 20, 'AKTIF'), 'score varchar(2) DEFAULT NULL', 'note varchar(255) DEFAULT NULL'], ['UNIQUE KEY uq_em (extracurricular_id, student_id)', fk('em_ekskul', 'extracurricular_id', 'extracurriculars')]),
    tenantTable('achievements', ['student_id char(36) NOT NULL', 'title varchar(200) NOT NULL', vs('level', 20, 'SEKOLAH'), 'rank_label varchar(40) DEFAULT NULL', 'organizer varchar(200) DEFAULT NULL', 'achieved_at date DEFAULT NULL', 'certificate_file_id char(36) DEFAULT NULL', 'is_public tinyint(1) NOT NULL DEFAULT 0'], ['KEY idx_ach_student (student_id)']),

    // ---- Keuangan ----
    tenantTable('fee_types', ['code varchar(20) NOT NULL', 'name varchar(120) NOT NULL', money('default_amount'), vs('period', 10, 'BULANAN'), 'is_active tinyint(1) NOT NULL DEFAULT 1'], ['UNIQUE KEY uq_fee (tenant_id, code)']),
    tenantTable('late_fee_rules', ['fee_type_id char(36) DEFAULT NULL', 'grace_days smallint NOT NULL DEFAULT 0', vs('mode', 10, 'FLAT'), 'amount decimal(15,2) NOT NULL DEFAULT 0', 'max_amount decimal(15,2) DEFAULT NULL', 'is_active tinyint(1) NOT NULL DEFAULT 1']),
    tenantTable('invoices', [
      'number varchar(40) NOT NULL', 'student_id char(36) NOT NULL', 'academic_year_id char(36) DEFAULT NULL', 'fee_type_id char(36) DEFAULT NULL', 'title varchar(200) NOT NULL', 'period varchar(7) DEFAULT NULL',
      money('amount'), money('discount'), money('late_fee'), money('paid'), 'due_date date DEFAULT NULL', vs('status', 20, 'UNPAID'), 'note varchar(255) DEFAULT NULL', 'created_by char(36) DEFAULT NULL',
    ], ['UNIQUE KEY uq_inv_number (tenant_id, number)', 'KEY idx_inv_student (student_id, status)', 'KEY idx_inv_due (tenant_id, due_date)']),
    tenantTable('payments', ['number varchar(40) NOT NULL', 'student_id char(36) NOT NULL', money('amount'), vs('method', 20, 'TUNAI'), 'reference varchar(100) DEFAULT NULL', 'paid_at datetime NOT NULL', 'received_by char(36) DEFAULT NULL', 'note varchar(255) DEFAULT NULL', vs('status', 20, 'CONFIRMED'), 'proof_file_id char(36) DEFAULT NULL'], ['UNIQUE KEY uq_pay_number (tenant_id, number)', 'KEY idx_pay_student (student_id, paid_at)']),
    table('payment_allocations', [ID, 'payment_id char(36) NOT NULL', 'invoice_id char(36) NOT NULL', money('amount'), 'PRIMARY KEY (id)', 'KEY idx_pa_inv (invoice_id)', fk('pa_payment', 'payment_id', 'payments'), fk('pa_invoice', 'invoice_id', 'invoices')]),
    tenantTable('refunds', ['payment_id char(36) DEFAULT NULL', 'student_id char(36) NOT NULL', money('amount'), 'reason text', vs('status', 20, 'PENDING'), 'approved_by char(36) DEFAULT NULL', 'approved_at datetime DEFAULT NULL', 'paid_at datetime DEFAULT NULL', 'created_by char(36) DEFAULT NULL'], ['KEY idx_refund_student (student_id)']),
    tenantTable('reconciliation_batches', ['file_name varchar(255) DEFAULT NULL', 'bank_name varchar(60) DEFAULT NULL', 'total_rows int NOT NULL DEFAULT 0', 'matched int NOT NULL DEFAULT 0', 'unmatched int NOT NULL DEFAULT 0', vs('status', 20, 'DONE'), 'created_by char(36) DEFAULT NULL']),
    table('reconciliation_items', [ID, 'batch_id char(36) NOT NULL', 'tx_date date DEFAULT NULL', 'description varchar(255) DEFAULT NULL', 'amount decimal(15,2) NOT NULL DEFAULT 0', 'reference varchar(100) DEFAULT NULL', 'payment_id char(36) DEFAULT NULL', vs('status', 20, 'UNMATCHED'), 'PRIMARY KEY (id)', 'KEY idx_rci_batch (batch_id)', fk('rci_batch', 'batch_id', 'reconciliation_batches')]),
    tenantTable('cash_flows', ['tx_date date NOT NULL', vs('direction', 3, 'IN'), 'category varchar(60) NOT NULL', money('amount'), 'description varchar(255) DEFAULT NULL', 'reference_type varchar(30) DEFAULT NULL', 'reference_id char(36) DEFAULT NULL', 'created_by char(36) DEFAULT NULL'], ['KEY idx_cf_date (tenant_id, tx_date)']),

    // ---- Payroll ----
    tenantTable('job_positions', ['code varchar(20) NOT NULL', 'name varchar(120) NOT NULL', 'base_salary decimal(15,2) NOT NULL DEFAULT 0', 'is_active tinyint(1) NOT NULL DEFAULT 1'], ['UNIQUE KEY uq_jp (tenant_id, code)']),
    tenantTable('payroll_components', ['code varchar(20) NOT NULL', 'name varchar(120) NOT NULL', vs('kind', 10, 'ALLOWANCE'), vs('calc', 10, 'FIXED'), 'default_amount decimal(15,2) NOT NULL DEFAULT 0', 'taxable tinyint(1) NOT NULL DEFAULT 1', 'order_no int NOT NULL DEFAULT 0', 'is_active tinyint(1) NOT NULL DEFAULT 1'], ['UNIQUE KEY uq_pc (tenant_id, code)']),
    tenantTable('salary_structures', ['user_id char(36) NOT NULL', 'component_id char(36) NOT NULL', 'amount decimal(15,2) NOT NULL DEFAULT 0', 'effective_from date DEFAULT NULL'], ['UNIQUE KEY uq_ss (user_id, component_id)', fk('ss_comp', 'component_id', 'payroll_components')]),
    tenantTable('payroll_period_configs', ['pay_day tinyint NOT NULL DEFAULT 25', 'bpjs_kes_employee decimal(5,2) NOT NULL DEFAULT 1', 'bpjs_kes_employer decimal(5,2) NOT NULL DEFAULT 4', 'bpjs_tk_jht_employee decimal(5,2) NOT NULL DEFAULT 2', 'bpjs_tk_jht_employer decimal(5,2) NOT NULL DEFAULT 3.7', 'bpjs_tk_jp_employee decimal(5,2) NOT NULL DEFAULT 1', 'bpjs_tk_jp_employer decimal(5,2) NOT NULL DEFAULT 2', 'bpjs_tk_jkk decimal(5,2) NOT NULL DEFAULT 0.24', 'bpjs_tk_jkm decimal(5,2) NOT NULL DEFAULT 0.3', 'bpjs_kes_cap decimal(15,2) NOT NULL DEFAULT 12000000', 'apply_pph21 tinyint(1) NOT NULL DEFAULT 1'], ['UNIQUE KEY uq_ppc_tenant (tenant_id)']),
    tenantTable('payroll_runs', ['period varchar(7) NOT NULL', vs('status', 20, 'DRAFT'), 'total_gross decimal(15,2) NOT NULL DEFAULT 0', 'total_net decimal(15,2) NOT NULL DEFAULT 0', 'employee_count int NOT NULL DEFAULT 0', 'validated_by char(36) DEFAULT NULL', 'finance_approved_by char(36) DEFAULT NULL', 'principal_approved_by char(36) DEFAULT NULL', 'paid_at datetime DEFAULT NULL', 'note varchar(255) DEFAULT NULL', 'created_by char(36) DEFAULT NULL'], ['UNIQUE KEY uq_pr_period (tenant_id, period)']),
    table('payroll_run_items', [ID, 'run_id char(36) NOT NULL', 'user_id char(36) NOT NULL', 'gross decimal(15,2) NOT NULL DEFAULT 0', 'deductions decimal(15,2) NOT NULL DEFAULT 0', 'bpjs_employee decimal(15,2) NOT NULL DEFAULT 0', 'bpjs_employer decimal(15,2) NOT NULL DEFAULT 0', 'pph21 decimal(15,2) NOT NULL DEFAULT 0', 'net decimal(15,2) NOT NULL DEFAULT 0', 'detail_lines json DEFAULT NULL', 'attendance_days smallint DEFAULT NULL', 'PRIMARY KEY (id)', 'UNIQUE KEY uq_pri (run_id, user_id)', fk('pri_run', 'run_id', 'payroll_runs')]),
    tenantTable('payslips', ['run_item_id char(36) NOT NULL', 'user_id char(36) NOT NULL', 'period varchar(7) NOT NULL', 'pdf_file_id char(36) DEFAULT NULL', 'issued_at datetime DEFAULT NULL', 'viewed_at datetime DEFAULT NULL'], ['UNIQUE KEY uq_slip (run_item_id)', 'KEY idx_slip_user (user_id, period)']),
  ],
};
