import { Migration, table, tenantTable, fk, ID, vs, money } from './ddl';

export const m0007: Migration = {
  name: '0007_assets_ppdb_smk',
  statements: [
    // ---- Aset ----
    tenantTable('assets', ['code varchar(30) NOT NULL', 'name varchar(150) NOT NULL', vs('category', 40, 'ELEKTRONIK'), 'location varchar(120) DEFAULT NULL', 'room_id char(36) DEFAULT NULL', 'purchase_date date DEFAULT NULL', money('purchase_price'), 'useful_life_years smallint NOT NULL DEFAULT 5', 'salvage_value decimal(15,2) NOT NULL DEFAULT 0', vs('condition_status', 20, 'BAIK'), vs('status', 20, 'AKTIF'), 'quantity int NOT NULL DEFAULT 1', 'custodian_id char(36) DEFAULT NULL', 'notes text', 'photo_file_id char(36) DEFAULT NULL'], ['UNIQUE KEY uq_asset_code (tenant_id, code)']),
    tenantTable('asset_bookings', ['asset_id char(36) NOT NULL', 'booked_by char(36) NOT NULL', 'start_at datetime NOT NULL', 'end_at datetime NOT NULL', 'purpose varchar(255) DEFAULT NULL', vs('status', 20, 'PENDING'), 'approved_by char(36) DEFAULT NULL', 'returned_at datetime DEFAULT NULL', 'return_condition varchar(20) DEFAULT NULL'], ['KEY idx_ab_asset_time (asset_id, start_at, end_at)', fk('ab_asset', 'asset_id', 'assets')]),
    tenantTable('asset_maintenance', ['asset_id char(36) NOT NULL', 'scheduled_date date NOT NULL', 'done_date date DEFAULT NULL', vs('type', 20, 'RUTIN'), 'description text', money('cost'), 'vendor varchar(150) DEFAULT NULL', vs('status', 20, 'SCHEDULED'), 'created_by char(36) DEFAULT NULL'], ['KEY idx_am_asset (asset_id, scheduled_date)', fk('am_asset', 'asset_id', 'assets')]),
    tenantTable('asset_audits', ['title varchar(150) NOT NULL', 'audit_date date NOT NULL', vs('status', 20, 'OPEN'), 'items json DEFAULT NULL', 'summary json DEFAULT NULL', 'created_by char(36) DEFAULT NULL', 'closed_at datetime DEFAULT NULL']),

    // ---- Perpustakaan ----
    tenantTable('library_books', ['isbn varchar(20) DEFAULT NULL', 'code varchar(30) NOT NULL', 'title varchar(200) NOT NULL', 'author varchar(150) DEFAULT NULL', 'publisher varchar(150) DEFAULT NULL', 'year smallint DEFAULT NULL', 'category varchar(60) DEFAULT NULL', 'stock int NOT NULL DEFAULT 1', 'available int NOT NULL DEFAULT 1', 'shelf varchar(30) DEFAULT NULL', 'cover_file_id char(36) DEFAULT NULL'], ['UNIQUE KEY uq_book_code (tenant_id, code)']),
    tenantTable('library_loans', ['book_id char(36) NOT NULL', 'borrower_id char(36) NOT NULL', 'borrowed_at date NOT NULL', 'due_at date NOT NULL', 'returned_at date DEFAULT NULL', vs('status', 20, 'BORROWED'), money('fine'), 'handled_by char(36) DEFAULT NULL'], ['KEY idx_loan_book (book_id)', 'KEY idx_loan_borrower (borrower_id, status)', fk('loan_book', 'book_id', 'library_books')]),

    // ---- PPDB ----
    tenantTable('ppdb_periods', ['name varchar(120) NOT NULL', 'academic_year_id char(36) DEFAULT NULL', 'open_at datetime NOT NULL', 'close_at datetime NOT NULL', 'quota int NOT NULL DEFAULT 0', 'requirements json DEFAULT NULL', 'paths json DEFAULT NULL', 'is_active tinyint(1) NOT NULL DEFAULT 1', 'announcement text']),
    tenantTable('ppdb_applicants', [
      'period_id char(36) NOT NULL', 'registration_no varchar(30) NOT NULL', 'user_id char(36) DEFAULT NULL', 'full_name varchar(150) NOT NULL', 'nisn varchar(20) DEFAULT NULL', 'nik varchar(20) DEFAULT NULL', 'gender char(1) DEFAULT NULL',
      'birth_place varchar(100) DEFAULT NULL', 'birth_date date DEFAULT NULL', 'origin_school varchar(200) DEFAULT NULL', 'address text', 'phone varchar(30) DEFAULT NULL', 'email varchar(190) DEFAULT NULL',
      'parent_name varchar(150) DEFAULT NULL', 'parent_phone varchar(30) DEFAULT NULL', 'major_choice_1 char(36) DEFAULT NULL', 'major_choice_2 char(36) DEFAULT NULL', 'path varchar(30) DEFAULT NULL',
      'access_token char(64) DEFAULT NULL', vs('status', 20, 'SUBMITTED'), 'score decimal(6,2) DEFAULT NULL', 'verified_by char(36) DEFAULT NULL', 'verified_at datetime DEFAULT NULL', 'verification_note varchar(255) DEFAULT NULL',
      'accepted_major_id char(36) DEFAULT NULL', 'enrolled_user_id char(36) DEFAULT NULL', 'enrolled_class_id char(36) DEFAULT NULL',
    ], ['UNIQUE KEY uq_ppdb_regno (tenant_id, registration_no)', 'KEY idx_ppdb_period_status (period_id, status)', 'KEY idx_ppdb_token (access_token)', fk('ppdb_period', 'period_id', 'ppdb_periods')]),
    table('ppdb_documents', [ID, 'applicant_id char(36) NOT NULL', 'doc_type varchar(40) NOT NULL', 'file_id char(36) NOT NULL', vs('status', 20, 'UPLOADED'), 'note varchar(255) DEFAULT NULL', 'created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP', 'PRIMARY KEY (id)', 'KEY idx_pd_app (applicant_id)', fk('pd_app', 'applicant_id', 'ppdb_applicants')]),

    // ---- SMK: prakerin & uji kompetensi ----
    tenantTable('industry_partners', ['name varchar(200) NOT NULL', 'sector varchar(100) DEFAULT NULL', 'address text', 'city varchar(100) DEFAULT NULL', 'contact_name varchar(150) DEFAULT NULL', 'contact_phone varchar(30) DEFAULT NULL', 'contact_email varchar(190) DEFAULT NULL', 'mou_number varchar(80) DEFAULT NULL', 'mou_until date DEFAULT NULL', 'quota smallint NOT NULL DEFAULT 0', 'is_active tinyint(1) NOT NULL DEFAULT 1']),
    tenantTable('industry_mentors', ['partner_id char(36) NOT NULL', 'user_id char(36) DEFAULT NULL', 'name varchar(150) NOT NULL', 'position varchar(100) DEFAULT NULL', 'phone varchar(30) DEFAULT NULL', 'email varchar(190) DEFAULT NULL'], ['KEY idx_im_partner (partner_id)', fk('im_partner', 'partner_id', 'industry_partners')]),
    tenantTable('internships', ['student_id char(36) NOT NULL', 'partner_id char(36) NOT NULL', 'mentor_id char(36) DEFAULT NULL', 'school_supervisor_id char(36) DEFAULT NULL', 'academic_year_id char(36) DEFAULT NULL', 'start_date date NOT NULL', 'end_date date NOT NULL', vs('status', 20, 'PLANNED'), 'final_score decimal(5,2) DEFAULT NULL', 'mentor_feedback text', 'certificate_file_id char(36) DEFAULT NULL'], ['KEY idx_int_student (student_id)', 'KEY idx_int_partner (partner_id)', 'KEY idx_int_mentor (mentor_id)']),
    tenantTable('internship_journals', ['internship_id char(36) NOT NULL', 'journal_date date NOT NULL', 'activity text NOT NULL', 'hours decimal(4,1) NOT NULL DEFAULT 8', 'photo_file_id char(36) DEFAULT NULL', vs('status', 20, 'SUBMITTED'), 'verified_by char(36) DEFAULT NULL', 'verified_at datetime DEFAULT NULL', 'mentor_note varchar(255) DEFAULT NULL'], ['UNIQUE KEY uq_ij (internship_id, journal_date)', fk('ij_int', 'internship_id', 'internships')]),
    tenantTable('competency_schemes', ['code varchar(30) NOT NULL', 'name varchar(200) NOT NULL', 'major_id char(36) DEFAULT NULL', 'description text', 'units json DEFAULT NULL', 'is_active tinyint(1) NOT NULL DEFAULT 1'], ['UNIQUE KEY uq_cscheme (tenant_id, code)']),
    tenantTable('competency_rubrics', ['scheme_id char(36) NOT NULL', 'code varchar(30) NOT NULL', 'criteria varchar(255) NOT NULL', 'max_score decimal(5,2) NOT NULL DEFAULT 100', 'weight decimal(5,2) NOT NULL DEFAULT 1', 'order_no int NOT NULL DEFAULT 0'], ['KEY idx_cr_scheme (scheme_id)', fk('cr_scheme', 'scheme_id', 'competency_schemes')]),
    tenantTable('competency_tests', ['scheme_id char(36) NOT NULL', 'title varchar(200) NOT NULL', 'test_date date NOT NULL', 'location varchar(150) DEFAULT NULL', 'external_examiner_id char(36) DEFAULT NULL', 'internal_examiner_id char(36) DEFAULT NULL', vs('status', 20, 'SCHEDULED'), 'note varchar(255) DEFAULT NULL'], ['KEY idx_ct_scheme (scheme_id)', 'KEY idx_ct_examiner (external_examiner_id)', fk('ct_scheme', 'scheme_id', 'competency_schemes')]),
    tenantTable('competency_results', ['test_id char(36) NOT NULL', 'student_id char(36) NOT NULL', 'scores json DEFAULT NULL', 'total_score decimal(6,2) DEFAULT NULL', vs('verdict', 20, 'PENDING'), 'examiner_note text', 'assessed_by char(36) DEFAULT NULL', 'assessed_at datetime DEFAULT NULL', 'certificate_file_id char(36) DEFAULT NULL'], ['UNIQUE KEY uq_cres (test_id, student_id)', fk('cres_test', 'test_id', 'competency_tests')]),

    // ---- PDP (UU Pelindungan Data Pribadi) ----
    tenantTable('consents', ['user_id char(36) NOT NULL', 'purpose varchar(80) NOT NULL', 'granted tinyint(1) NOT NULL DEFAULT 1', 'granted_at datetime DEFAULT NULL', 'revoked_at datetime DEFAULT NULL', 'ip varchar(64) DEFAULT NULL'], ['UNIQUE KEY uq_consent (user_id, purpose)']),
    tenantTable('pdp_requests', ['user_id char(36) NOT NULL', vs('type', 20, 'DELETE'), 'reason text', vs('status', 20, 'PENDING'), 'reviewed_by char(36) DEFAULT NULL', 'reviewed_at datetime DEFAULT NULL', 'review_note varchar(255) DEFAULT NULL', 'executed_at datetime DEFAULT NULL'], ['KEY idx_pdp_user (user_id)', 'KEY idx_pdp_status (tenant_id, status)']),
    tenantTable('retention_policies', ['entity varchar(60) NOT NULL', 'retention_months smallint NOT NULL DEFAULT 60', vs('action', 20, 'ANONYMIZE'), 'is_active tinyint(1) NOT NULL DEFAULT 1', 'last_run_at datetime DEFAULT NULL'], ['UNIQUE KEY uq_retention (tenant_id, entity)']),
  ],
};
