import { useState } from 'react';
import { ExternalLink, Image as ImageIcon } from 'lucide-react';
import { uploadFile, fileSrc } from '@/lib/api';
import { useAuth } from '@/store/auth';
import { CrudPage, FormField } from '@/features/crud/CrudPage';
import { Badge, Button, PageHeader, Tabs } from '@/components/ui';
import { fmtDate, fmtDateTime } from '@/lib/format';
import { Dict } from '@/lib/types';

const P = { write: 'landing:write' };
function ImageField({ value, onChange }: { value: unknown; onChange: (v: unknown) => void }) {
  return <div className="flex items-center gap-3">{value ? <span className="text-xs text-emerald-600">✓ berkas tersimpan</span> : <span className="text-xs text-ink-3">belum ada gambar</span>}<label className="cursor-pointer rounded-lg border border-line px-3 py-1.5 text-xs hover:bg-surface-3"><ImageIcon className="mr-1 inline h-3.5 w-3.5" />Unggah<input type="file" accept="image/*" className="hidden" onChange={async (e) => { const f = e.target.files?.[0]; if (f) { const up = await uploadFile('landing', f, true); onChange(up.id); } }} /></label></div>;
}
const img = (name: string, label: string): FormField => ({ name, label, type: 'custom', render: ({ value, onChange }) => <ImageField value={value} onChange={onChange} /> });
const pub = (): FormField => ({ name: 'is_published', label: 'Tayang', type: 'switch', defaultValue: true });
const order = (): FormField => ({ name: 'order_no', label: 'Urutan', type: 'number', defaultValue: 0 });
const thumb = (r: Dict, key = 'photo_url') => (r[key] ? <img src={fileSrc(r[key] as string)} className="h-10 w-14 rounded object-cover" alt="" /> : <div className="flex h-10 w-14 items-center justify-center rounded bg-surface-3"><ImageIcon className="h-4 w-4 text-ink-3" /></div>);

export default function LandingCms() {
  const { user } = useAuth();
  const [tab, setTab] = useState<'halaman' | 'berita' | 'fasilitas' | 'galeri' | 'testimoni' | 'faq' | 'pesan'>('halaman');
  const slug = user?.tenant?.slug;
  return (
    <div>
      <PageHeader title="Landing Page & Berita" subtitle="Konten situs publik lembaga. Tampil tanpa login." actions={<a href={`/s/${slug}`} target="_blank" rel="noreferrer"><Button variant="outline" icon={<ExternalLink className="h-4 w-4" />}>Lihat situs</Button></a>} />
      <Tabs className="mb-4 w-fit" value={tab} onChange={setTab} tabs={[{ value: 'halaman', label: 'Halaman' }, { value: 'berita', label: 'Berita' }, { value: 'fasilitas', label: 'Fasilitas' }, { value: 'galeri', label: 'Galeri' }, { value: 'testimoni', label: 'Testimoni' }, { value: 'faq', label: 'FAQ' }, { value: 'pesan', label: 'Pesan masuk' }]} />
      {tab === 'halaman' && <CrudPage<Dict> noHeader title="Halaman" endpoint="/landing/pages" entityLabel="halaman" modalSize="lg" perm={P} columns={[{ key: 'slug', header: 'Slug', render: (r) => <code className="text-xs">/{r.slug as string}</code> }, { key: 'title', header: 'Judul' }, { key: 'hero_title', header: 'Hero' }, { key: 'is_published', header: 'Tayang', render: (r) => <Badge tone={r.is_published ? 'green' : 'gray'}>{r.is_published ? 'Ya' : 'Draf'}</Badge> }, { key: 'order_no', header: 'Urutan', className: 'text-center' }]} fields={[{ name: 'slug', label: 'Slug', required: true, hint: 'home, tentang, program, …' }, { name: 'title', label: 'Judul', required: true }, { name: 'hero_title', label: 'Judul hero', span: 2 }, { name: 'hero_subtitle', label: 'Subjudul hero', type: 'textarea', span: 2 }, img('hero_image_file_id', 'Gambar hero'), { name: 'seo_description', label: 'Deskripsi SEO' }, { name: 'sections', label: 'Seksi (JSON: [{type:"text", title, body}] )', type: 'json', defaultValue: [{ type: 'text', title: 'Visi', body: '' }], span: 2 }, pub(), order()]} />}
      {tab === 'berita' && <CrudPage<Dict> noHeader title="Berita" endpoint="/landing/news" entityLabel="berita" modalSize="lg" perm={P} columns={[{ key: 'cover_url', header: '', render: (r) => thumb(r, 'cover_url') }, { key: 'title', header: 'Judul', render: (r) => <div><div className="font-medium">{r.title as string}</div><div className="text-xs text-ink-3">/{r.slug as string} · {r.category as string} · {r.author as string}</div></div> }, { key: 'published_at', header: 'Terbit', render: (r) => r.is_published ? fmtDateTime(r.published_at as string) : <Badge tone="gray">Draf</Badge> }, { key: 'view_count', header: 'Dilihat', className: 'text-center' }]} fields={[{ name: 'title', label: 'Judul', required: true, span: 2 }, { name: 'category', label: 'Kategori', placeholder: 'Kegiatan / Prestasi / Pengumuman' }, { name: 'slug', label: 'Slug (kosong = otomatis)' }, { name: 'excerpt', label: 'Ringkasan', type: 'textarea', span: 2 }, { name: 'body', label: 'Isi', type: 'textarea', span: 2 }, img('cover_file_id', 'Sampul'), { name: 'published_at', label: 'Tanggal terbit', type: 'datetime' }, pub()]} />}
      {tab === 'fasilitas' && <CrudPage<Dict> noHeader title="Fasilitas" endpoint="/landing/facilities" entityLabel="fasilitas" perm={P} columns={[{ key: 'photo_url', header: '', render: (r) => thumb(r) }, { key: 'name', header: 'Nama' }, { key: 'description', header: 'Deskripsi', render: (r) => <span className="line-clamp-2 text-sm">{r.description as string}</span> }, { key: 'is_published', header: 'Tayang', render: (r) => (r.is_published ? 'Ya' : '-') }]} fields={[{ name: 'name', label: 'Nama', required: true, span: 2 }, { name: 'description', label: 'Deskripsi', type: 'textarea', span: 2 }, img('photo_file_id', 'Foto'), order(), pub()]} />}
      {tab === 'galeri' && <CrudPage<Dict> noHeader title="Galeri" endpoint="/landing/gallery" entityLabel="foto" perm={P} columns={[{ key: 'file_url', header: '', render: (r) => thumb(r, 'file_url') }, { key: 'title', header: 'Judul' }, { key: 'album', header: 'Album' }, { key: 'created_at', header: 'Diunggah', render: (r) => fmtDate(r.created_at as string) }]} filters={[{ name: 'album', label: 'Album', type: 'text' }]} fields={[{ name: 'title', label: 'Judul' }, { name: 'album', label: 'Album' }, img('file_id', 'Foto'), order(), pub()]} />}
      {tab === 'testimoni' && <CrudPage<Dict> noHeader title="Testimoni" endpoint="/landing/testimonials" entityLabel="testimoni" perm={P} columns={[{ key: 'photo_url', header: '', render: (r) => thumb(r) }, { key: 'name', header: 'Nama', render: (r) => <div>{r.name as string}<div className="text-xs text-ink-3">{r.role_label as string}</div></div> }, { key: 'quote', header: 'Kutipan', render: (r) => <span className="line-clamp-2 text-sm italic">“{r.quote as string}”</span> }, { key: 'is_published', header: 'Tayang', render: (r) => (r.is_published ? 'Ya' : '-') }]} fields={[{ name: 'name', label: 'Nama', required: true }, { name: 'role_label', label: 'Peran / afiliasi' }, { name: 'quote', label: 'Kutipan', type: 'textarea', required: true, span: 2 }, img('photo_file_id', 'Foto'), order(), pub()]} />}
      {tab === 'faq' && <CrudPage<Dict> noHeader title="FAQ" endpoint="/landing/faqs" entityLabel="FAQ" perm={P} columns={[{ key: 'question', header: 'Pertanyaan' }, { key: 'category', header: 'Kategori' }, { key: 'is_published', header: 'Tayang', render: (r) => (r.is_published ? 'Ya' : '-') }]} fields={[{ name: 'question', label: 'Pertanyaan', required: true, span: 2 }, { name: 'answer', label: 'Jawaban', type: 'textarea', required: true, span: 2 }, { name: 'category', label: 'Kategori' }, order(), pub()]} />}
      {tab === 'pesan' && <CrudPage<Dict> noHeader title="Pesan masuk" endpoint="/landing/contact-messages" entityLabel="pesan" perm={P} canCreate={false} columns={[{ key: 'created_at', header: 'Waktu', render: (r) => fmtDateTime(r.created_at as string) }, { key: 'name', header: 'Pengirim', render: (r) => <div>{r.name as string}<div className="text-xs text-ink-3">{r.email as string} {r.phone as string}</div></div> }, { key: 'subject', header: 'Subjek' }, { key: 'message', header: 'Pesan', render: (r) => <span className="line-clamp-2 max-w-md text-sm">{r.message as string}</span> }, { key: 'status', header: 'Status', render: (r) => <Badge tone={r.status === 'NEW' ? 'amber' : 'gray'}>{r.status as string}</Badge> }]} filters={[{ name: 'status', label: 'Status', options: ['NEW', 'READ', 'REPLIED', 'ARCHIVED'].map((x) => ({ value: x, label: x })) }]} fields={[{ name: 'status', label: 'Status', type: 'select', options: ['NEW', 'READ', 'REPLIED', 'ARCHIVED'].map((x) => ({ value: x, label: x })) }]} />}
    </div>
  );
}
